function initProdutos() {
  if (!localStorage.getItem("produtos")) {
    const produtos = [
        {
        "id": 1,
        "nome": "Maçã Gala Fresca",
        "preco": 18.99,
        "descricao": "Maçãs tipo Gala selecionadas, crocantes e levemente adocicadas. Embalagem com aproximadamente 1 kg.",
        "imagem": "https://png.pngtree.com/png-clipart/20240824/original/pngtree-fresh-royal-gala-apples-whole-juicy-photo-png-image_15844082.png",
        "estoque": 71,
        "vendidos": 70,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 2,
        "nome": "Banana Prata Orgânica",
        "preco": 23.35,
        "descricao": "Bananas Prata de cultivo orgânico, sabor suave e textura firme. Embalagem com cerca de 1 kg.",
        "imagem": "https://png.pngtree.com/png-clipart/20250117/original/pngtree-one-dozen-fresh-banana-in-the-basket-png-image_19717788.png",
        "estoque": 59,
        "vendidos": 28,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 3,
        "nome": "Mamão Formosa Maduro",
        "preco": 13.19,
        "descricao": "Mamão Formosa maduro, ideal para sucos ou consumo direto. Aproximadamente 613g por unidade.",
        "imagem": "https://png.pngtree.com/png-clipart/20241217/original/pngtree-ripe-papayas-isolated-on-white-transparent-background-png-image_17954226.png",
        "estoque": 73,
        "vendidos": 4,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 4,
        "nome": "Melancia Doce",
        "preco": 15.12,
        "descricao": "Melancia com polpa vermelha, doce e refrescante. Aproximadamente 559g por porção.",
        "imagem": "https://static.vecteezy.com/system/resources/previews/029/200/216/non_2x/watermelon-transparent-background-free-png.png",
        "estoque": 42,
        "vendidos": 73,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 5,
        "nome": "Manga Palmer",
        "preco": 23.64,
        "descricao": "Mangas Palmer maduras, com polpa firme e sem fiapos. Embalagem com cerca de 956g.",
        "imagem": "https://lh6.googleusercontent.com/proxy/xMbwWI08yLRt1L1Brj5heNZNTqkTAQAshW2lnxLN3CZeqCiP5AkAYvs53PS9cB6eI72rU058kodcTAdqUNS9oH4ggOMbshwApVxf0zswLbnczhVInltDHw",
        "estoque": 40,
        "vendidos": 60,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 6,
        "nome": "Abacaxi Pérola",
        "preco": 19.89,
        "descricao": "Abacaxi da variedade Pérola, sabor doce e acidez equilibrada. Embalagem com aproximadamente 241g.",
        "imagem": "https://phygital-files.mercafacil.com/big_mart/uploads/produto/abacaxi_perola_un_9ace93e4-0f9b-4de0-8398-95a88b4070b6.png",
        "estoque": 58,
        "vendidos": 62,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 7,
        "nome": "Uva Rubi",
        "preco": 23.62,
        "descricao": "Uvas Rubi frescas, firmes e sem sementes. Embalagem padrão com cerca de 620g.",
        "imagem": "https://acdn-us.mitiendanube.com/stores/001/194/977/products/uva-rubi1-2bbfb07f852f72ab4b15897576254427-480-0.jpg",
        "estoque": 12,
        "vendidos": 68,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 8,
        "nome": "Kiwi Importado",
        "preco": 14.25,
        "descricao": "Kiwis verdes importados, ricos em vitamina C. Embalagem padrão com 888g aproximadamente.",
        "imagem": "https://static.vecteezy.com/system/resources/previews/015/100/080/non_2x/kiwi-fruit-transparent-background-free-png.png",
        "estoque": 93,
        "vendidos": 72,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 9,
        "nome": "Pera Willians",
        "preco": 17.84,
        "descricao": "Peras Willians frescas, suculentas e aromáticas. Embalagem com cerca de 476g.",
        "imagem": "https://png.pngtree.com/thumb_back/fh260/background/20220719/pngtree-green-pears-isolated-on-white-background-diet-williams-pear-photo-image_26838440.jpg",
        "estoque": 13,
        "vendidos": 75,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 10,
        "nome": "Laranja Bahia",
        "preco": 13.03,
        "descricao": "Laranjas da variedade Bahia, ideais para sucos. Embalagem com aproximadamente 429g.",
        "imagem": "https://ibassets.com.br/ib.item.image.large/l-0c92a27787154a9db42f6777e5daa995.png",
        "estoque": 64,
        "vendidos": 45,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 11,
        "nome": "Morango Fresco Selecionado",
        "preco": 3.15,
        "descricao": "Morangos vermelhos e doces, lavados e prontos para consumo. Embalagem com 500g.",
        "imagem": "https://png.pngtree.com/png-clipart/20220922/original/pngtree-fresh-juicy-strawberry-fruit-transparent-background-png-image_8626838.png",
        "estoque": 60,
        "vendidos": 57,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 12,
        "nome": "Limão Tahiti",
        "preco": 9.08,
        "descricao": "Limões da variedade Tahiti, frescos e aromáticos. Embalagem com aproximadamente 662g.",
        "imagem": "https://st2.depositphotos.com/1006597/6549/i/450/depositphotos_65490531-stock-photo-fresh-limes.jpg",
        "estoque": 55,
        "vendidos": 22,
        "categoria": "Frutas",
        "marca": "Nest Fresh",
        "apresentacao": "por kg"
    },
    {
        "id": 13,
        "nome": "Cenoura Orgânica",
        "preco": 10.31,
        "descricao": "Cenouras frescas cultivadas sem agrotóxicos, ideais para saladas e cozidos. Embalagem com aproximadamente 1 kg.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 92,
        "vendidos": 44,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 14,
        "nome": "Batata Inglesa",
        "preco": 21.22,
        "descricao": "Batatas tipo inglesa, perfeitas para purê, assados e frituras. Embalagem com aproximadamente 416g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 80,
        "vendidos": 79,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 15,
        "nome": "Alface Crespa",
        "preco": 18.37,
        "descricao": "Folhas de alface crespa frescas, crocantes e ideais para saladas. Embalagem com cerca de 224g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 81,
        "vendidos": 52,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 16,
        "nome": "Couve Manteiga",
        "preco": 4.91,
        "descricao": "Couve manteiga fresca, ideal para refogados e sucos verdes. Embalagem com aproximadamente 292g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 76,
        "vendidos": 36,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 17,
        "nome": "Tomate Italiano Maduro",
        "preco": 7.27,
        "descricao": "Tomates italianos maduros, com polpa firme e pouca acidez. Ideais para molhos e saladas. Embalagem padrão.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 54,
        "vendidos": 9,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 18,
        "nome": "Brócolis Ninja",
        "preco": 17.24,
        "descricao": "Brócolis da variedade ninja, ricos em fibras e antioxidantes. Embalagem com cerca de 978g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 63,
        "vendidos": 58,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 19,
        "nome": "Espinafre Fresco",
        "preco": 24.25,
        "descricao": "Espinafre com folhas tenras, ideal para refogados e tortas. Embalagem com aproximadamente 959g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 55,
        "vendidos": 8,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 20,
        "nome": "Abobrinha Italiana",
        "preco": 9.66,
        "descricao": "Abobrinha italiana fresca, ótima para grelhar ou refogar. Embalagem com cerca de 553g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 57,
        "vendidos": 4,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 21,
        "nome": "Rúcula Hidropônica",
        "preco": 11.65,
        "descricao": "Rúcula hidropônica fresca e levemente picante. Ideal para saladas e sanduíches. Embalagem com 307g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 26,
        "vendidos": 78,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 22,
        "nome": "Pimentão Vermelho",
        "preco": 24.95,
        "descricao": "Pimentões vermelhos doces e crocantes, perfeitos para rechear ou refogar. Embalagem com aproximadamente 901g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 40,
        "vendidos": 53,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 23,
        "nome": "Pepino Japonês",
        "preco": 23.81,
        "descricao": "Pepinos japoneses com casca fina e sabor suave. Ideais para saladas. Embalagem com cerca de 282g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 40,
        "vendidos": 71,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    {
        "id": 24,
        "nome": "Cebola Amarela",
        "preco": 24.96,
        "descricao": "Cebolas amarelas com sabor equilibrado, ideais para refogados e ensopados. Embalagem com aproximadamente 798g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 57,
        "vendidos": 9,
        "categoria": "Vegetais",
        "marca": "VerdeSul",
        "apresentacao": "por kg"
    },
    
    {
        "id": 25,
        "nome": "Filé de frango",
        "preco": 6.99,
        "descricao": "Filé de peito de frango sem pele, ideal para grelhar, assar ou empanar. Aproximadamente 351g por embalagem.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 38,
        "vendidos": 38,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 26,
        "nome": "Carne moída",
        "preco": 13.4,
        "descricao": "Carne bovina moída de primeira, excelente para molhos, recheios e hambúrgueres. Embalagem com cerca de 549g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 61,
        "vendidos": 0,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 27,
        "nome": "Picanha",
        "preco": 10.35,
        "descricao": "Corte nobre da picanha com capa de gordura, ideal para churrasco. Aproximadamente 179g por peça.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 59,
        "vendidos": 19,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 28,
        "nome": "Costela",
        "preco": 23.22,
        "descricao": "Costela bovina com osso, sabor marcante e textura macia após cozimento lento. Embalagem com 838g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 84,
        "vendidos": 5,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 29,
        "nome": "Linguiça",
        "preco": 18.63,
        "descricao": "Linguiça suína temperada, pronta para grelha ou forno. Embalagem com aproximadamente 962g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 47,
        "vendidos": 2,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 30,
        "nome": "Coxa de frango",
        "preco": 6.53,
        "descricao": "Coxas de frango com pele e osso, ideais para assar ou ensopar. Embalagem com cerca de 935g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 52,
        "vendidos": 62,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 31,
        "nome": "Carne suína",
        "preco": 4.78,
        "descricao": "Corte suíno selecionado, sabor suave e versátil para grelhar, assar ou cozinhar. Embalagem com 563g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 11,
        "vendidos": 72,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 32,
        "nome": "Frango inteiro",
        "preco": 3.6,
        "descricao": "Frango inteiro resfriado, ideal para preparo assado ou cozido. Peso aproximado de 786g por unidade.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 76,
        "vendidos": 59,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 33,
        "nome": "Bife ancho",
        "preco": 14.37,
        "descricao": "Corte nobre de bife ancho com marmoreio acentuado, ideal para grelha. Aproximadamente 777g por peça.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 92,
        "vendidos": 45,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 34,
        "nome": "Maminha",
        "preco": 3.93,
        "descricao": "Maminha bovina macia, excelente para assados ou grelhados. Embalagem com 814g aproximadamente.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 67,
        "vendidos": 59,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 35,
        "nome": "Cupim",
        "preco": 9.28,
        "descricao": "Cupim bovino marmorizado, ideal para cozimento lento e churrasco. Embalagem com cerca de 468g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 86,
        "vendidos": 1,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    {
        "id": 36,
        "nome": "Alcatra",
        "preco": 2.8,
        "descricao": "Corte traseiro de alcatra, versátil para grelhar, assar ou refogar. Embalagem com aproximadamente 118g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 75,
        "vendidos": 25,
        "categoria": "Carnes",
        "marca": "Boa Fazenda",
        "apresentacao": "por kg"
    },
    
  {
    "id": 37,
    "nome": "Hambúrguer",
    "preco": 3.11,
    "descricao": "Hambúrguer grelhado de carne bovina com tempero especial, pronto para consumo. Peso aproximado: 945g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 48,
    "vendidos": 34,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 38,
    "nome": "Nuggets",
    "preco": 23.53,
    "descricao": "Nuggets crocantes de frango empanado, prontos para fritar ou assar. Porção de aproximadamente 788g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 67,
    "vendidos": 54,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 39,
    "nome": "Mini pizza",
    "preco": 9.51,
    "descricao": "Mini pizza individual com recheio de queijo e molho de tomate. Embalagem com 383g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 43,
    "vendidos": 31,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 40,
    "nome": "Empanado",
    "preco": 4.96,
    "descricao": "Filé de frango empanado e crocante, ideal para lanche rápido. Porção de 353g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 75,
    "vendidos": 14,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 41,
    "nome": "Croquete",
    "preco": 24.62,
    "descricao": "Croquete de carne temperada, crocante por fora e macio por dentro. Porção de 195g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 81,
    "vendidos": 49,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 42,
    "nome": "Pastel",
    "preco": 9.06,
    "descricao": "Pastel frito com recheio de carne e queijo, pronto para consumo. Porção de 713g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 80,
    "vendidos": 21,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 43,
    "nome": "Mini hot dog",
    "preco": 17.2,
    "descricao": "Mini cachorro-quente com pão macio e salsicha cozida. Embalagem com 866g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 68,
    "vendidos": 63,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 44,
    "nome": "Esfiha",
    "preco": 11.0,
    "descricao": "Esfiha aberta com recheio de carne moída temperada. Porção de 202g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 85,
    "vendidos": 64,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 45,
    "nome": "Coxinha",
    "preco": 21.52,
    "descricao": "Coxinha tradicional recheada com frango desfiado e massa macia. Peso aproximado de 998g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 76,
    "vendidos": 45,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 46,
    "nome": "Quibe",
    "preco": 22.96,
    "descricao": "Quibe de trigo e carne moída com tempero árabe tradicional. Porção de 633g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 93,
    "vendidos": 35,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 47,
    "nome": "Wrap",
    "preco": 10.89,
    "descricao": "Wrap de frango com vegetais frescos e molho especial, pronto para consumo. Embalagem com 442g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 67,
    "vendidos": 73,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
  {
    "id": 48,
    "nome": "Bauru",
    "preco": 11.52,
    "descricao": "Sanduíche Bauru tradicional com queijo, presunto e tomate no pão francês. Porção de 215g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 26,
    "vendidos": 70,
    "categoria": "Lanches",
    "marca": "GrillHouse",
    "apresentacao": "unidade"
  },
    
  {
    "id": 49,
    "nome": "Pizza",
    "preco": 23.12,
    "descricao": "Pizza congelada com cobertura de queijo e molho de tomate, pronta para forno. Peso aproximado de 930g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 59,
    "vendidos": 26,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 50,
    "nome": "Lasanha",
    "preco": 21.07,
    "descricao": "Lasanha congelada com camadas de massa, carne moída e molho branco. Embalagem com 455g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 88,
    "vendidos": 0,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 51,
    "nome": "Sorvete",
    "preco": 6.76,
    "descricao": "Pote de sorvete cremoso sabor baunilha. Embalagem de 500g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 88,
    "vendidos": 57,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 52,
    "nome": "Ervilha congelado",
    "preco": 9.82,
    "descricao": "Ervilhas verdes congeladas, ideais para acompanhamentos. Embalagem com 722g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 25,
    "vendidos": 35,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 53,
    "nome": "Milho congelado",
    "preco": 20.63,
    "descricao": "Grãos de milho doce congelado, prontos para uso culinário. Embalagem com 248g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 88,
    "vendidos": 21,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 54,
    "nome": "Mandioca congelado",
    "preco": 6.57,
    "descricao": "Mandioca cozida e congelada, pronta para fritar ou aquecer. Embalagem com 264g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 96,
    "vendidos": 21,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 55,
    "nome": "Hambúrguer congelado",
    "preco": 10.07,
    "descricao": "Hambúrgueres de carne bovina congelados, prontos para grelhar. Pacote com 500g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 12,
    "vendidos": 35,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 56,
    "nome": "Frango empanado",
    "preco": 14.18,
    "descricao": "Filés de frango empanados congelados, crocantes após preparo. Caixa com 500g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 84,
    "vendidos": 22,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 57,
    "nome": "Batata frita",
    "preco": 21.08,
    "descricao": "Palitos de batata congelada prontos para fritura. Pacote de 1kg.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 53,
    "vendidos": 46,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 58,
    "nome": "Almondega",
    "preco": 4.17,
    "descricao": "Almôndegas bovinas congeladas, ideais para molhos e pratos rápidos. Pacote de 500g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 95,
    "vendidos": 46,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 59,
    "nome": "Panqueca",
    "preco": 4.98,
    "descricao": "Panquecas recheadas congeladas, prontas para forno ou micro-ondas. Caixa com 5 unidades.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 58,
    "vendidos": 57,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
  {
    "id": 60,
    "nome": "Torta",
    "preco": 17.71,
    "descricao": "Torta salgada congelada, recheada com frango e legumes. Peso aproximado de 500g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 70,
    "vendidos": 41,
    "categoria": "Congelados",
    "marca": "Forno Rápido",
    "apresentacao": "unidade"
  },
    
  {
    "id": 61,
    "nome": "Milho Enlatado",
    "preco": 9.45,
    "descricao": "Milho doce cozido em conserva, pronto para consumo. Lata com 300g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 13,
    "vendidos": 37,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 62,
    "nome": "Ervilha Enlatada",
    "preco": 9.49,
    "descricao": "Ervilhas verdes em conserva, ideais para saladas e guarnições. Lata com 300g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 33,
    "vendidos": 23,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 63,
    "nome": "Sardinha Enlatada",
    "preco": 9.86,
    "descricao": "Sardinhas inteiras em óleo vegetal. Lata com 400g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 15,
    "vendidos": 53,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 64,
    "nome": "Atum Enlatado",
    "preco": 10.99,
    "descricao": "Atum sólido em água com sal, pronto para receitas rápidas. Lata com 650g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 66,
    "vendidos": 34,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 65,
    "nome": "Feijão Enlatado",
    "preco": 20.7,
    "descricao": "Feijão carioca cozido e conservado em caldo leve. Lata com 600g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 74,
    "vendidos": 39,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 66,
    "nome": "Tomate Italiano em Conserva",
    "preco": 11.21,
    "descricao": "Tomates italianos pelados em molho, ideais para preparo de massas. Lata padrão.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 68,
    "vendidos": 41,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 67,
    "nome": "Seleta de legumes enlatada",
    "preco": 7.33,
    "descricao": "Mistura de legumes (milho, ervilha, cenoura) em conserva. Lata com 800g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 87,
    "vendidos": 31,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 68,
    "nome": "Grão-de-bico enlatado",
    "preco": 20.29,
    "descricao": "Grão-de-bico cozido em conserva, ideal para saladas e pastas. Lata com 400g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 21,
    "vendidos": 1,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 69,
    "nome": "Molho de Tomate Italiano",
    "preco": 17.23,
    "descricao": "Molho pronto à base de tomate italiano, ideal para massas. Embalagem padrão.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 99,
    "vendidos": 74,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 70,
    "nome": "Palmito enlatado",
    "preco": 14.2,
    "descricao": "Palmito de pupunha em conserva, cortado em rodelas. Lata com 1,8kg.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 29,
    "vendidos": 60,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 71,
    "nome": "Cogumelo Enlatado",
    "preco": 6.19,
    "descricao": "Cogumelos champignon fatiados em conserva. Lata com 600g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 21,
    "vendidos": 77,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
  {
    "id": 72,
    "nome": "Azeitona enlatada",
    "preco": 20.98,
    "descricao": "Azeitonas verdes sem caroço em salmoura. Lata com 550g.",
    "imagem": "../imagenes/pr9.png",
    "estoque": 68,
    "vendidos": 56,
    "categoria": "Enlatados",
    "marca": "Delícia",
    "apresentacao": "unidade"
  },
    
    {
        "id": 73,
        "nome": "Leite Integral UHT 1L",
        "preco": 18.17,
        "descricao": "Leite integral longa vida, embalado em caixa Tetra Pak de 1 litro.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 76,
        "vendidos": 20,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 74,
        "nome": "Queijo Prato",
        "preco": 18.8,
        "descricao": "Queijo tipo prato, ideal para lanches e sanduíches. Embalagem com 659g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 80,
        "vendidos": 25,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 75,
        "nome": "Iogurte engarrafado",
        "preco": 21.0,
        "descricao": "Iogurte natural líquido em garrafa de 500ml, pronto para consumo.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 93,
        "vendidos": 73,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 76,
        "nome": "Manteiga",
        "preco": 6.26,
        "descricao": "Manteiga cremosa com sal, ideal para pães e preparos culinários. Pote com 300g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 28,
        "vendidos": 61,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 77,
        "nome": "Requeijão Cremoso",
        "preco": 9.13,
        "descricao": "Requeijão cremoso tradicional, em pote plástico de 250g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 27,
        "vendidos": 38,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 78,
        "nome": "Creme de Leite UHT",
        "preco": 11.96,
        "descricao": "Creme de leite UHT, leve e prático, em embalagem Tetra Pak de 1 litro.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 34,
        "vendidos": 33,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 79,
        "nome": "Leite Condensado",
        "preco": 23.31,
        "descricao": "Leite condensado integral, ideal para sobremesas. Embalagem Tetra Pak de 1 litro.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 73,
        "vendidos": 1,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 80,
        "nome": "Queijo Minas Frescal",
        "preco": 6.32,
        "descricao": "Queijo Minas tipo frescal, macio e levemente ácido. Pacote com 1kg.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 38,
        "vendidos": 5,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 81,
        "nome": "Ricota Fresca",
        "preco": 10.27,
        "descricao": "Ricota fresca e leve, ideal para saladas e recheios. Pote com 300g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 90,
        "vendidos": 66,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 82,
        "nome": "Queijo Mussarela em Fatias",
        "preco": 12.58,
        "descricao": "Pacote de 282g com queijo mussarela fatiado, ideal para lanches e receitas.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 45,
        "vendidos": 10,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 83,
        "nome": "Queijo Parmesão Ralado",
        "preco": 18.17,
        "descricao": "Queijo parmesão ralado, ideal para massas e gratinados. Embalagem com 812g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 82,
        "vendidos": 3,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 84,
        "nome": "Iogurte Danone",
        "preco": 5.43,
        "descricao": "Iogurte cremoso sabor morango em pote com 315g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 25,
        "vendidos": 7,
        "categoria": "Laticínios",
        "marca": "Serra",
        "apresentacao": "unidade"
    },
    {
        "id": 85,
        "nome": "Suco de Laranja Natural",
        "preco": 23.84,
        "descricao": "Bebida natural de laranja, sem conservantes. Garrafa de 1 litro.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 16,
        "vendidos": 13,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 86,
        "nome": "Água",
        "preco": 24.85,
        "descricao": "Garrafa de água mineral de 500ml, ideal para consumo diário.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 37,
        "vendidos": 48,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 87,
        "nome": "Refrigerante",
        "preco": 16.48,
        "descricao": "Lata de refrigerante com 350ml, sabor tradicional.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 99,
        "vendidos": 23,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 88,
        "nome": "Chá gelado",
        "preco": 15.93,
        "descricao": "Garrafa de 1 litro de chá gelado sabor pêssego.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 56,
        "vendidos": 37,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 89,
        "nome": "Energético",
        "preco": 16.35,
        "descricao": "Lata de energético com 269ml, com cafeína e taurina.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 97,
        "vendidos": 19,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 90,
        "nome": "Suco de uva",
        "preco": 10.38,
        "descricao": "Suco integral de uva, 1 litro, sem adição de açúcar.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 75,
        "vendidos": 49,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 91,
        "nome": "Água de coco",
        "preco": 7.27,
        "descricao": "Bebida natural de água de coco, garrafa de 330ml.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 12,
        "vendidos": 32,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 92,
        "nome": "Cerveja",
        "preco": 3.32,
        "descricao": "Lata de cerveja pilsen 350ml, gelada e refrescante.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 80,
        "vendidos": 29,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 93,
        "nome": "Vinho",
        "preco": 7.92,
        "descricao": "Garrafa de vinho tinto seco 750ml, ideal para harmonizações.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 26,
        "vendidos": 52,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 94,
        "nome": "Smoothie",
        "preco": 16.0,
        "descricao": "Garrafa de smoothie 300ml, combinação de frutas e iogurte.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 57,
        "vendidos": 35,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
        "id": 95,
        "nome": "Suco detox",
        "preco": 4.41,
        "descricao": "Suco funcional detox, garrafa de 300ml, com ingredientes naturais.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 85,
        "vendidos": 63,
        "categoria": "Bebidas",
        "marca": "EcoFresh",
        "apresentacao": "unidade"
    },
    {
      "id": 96,
      "nome": "Isotônico",
      "preco": 17.78,
      "descricao": "Garrafa de isotônico 500ml, repõe sais minerais e energia.",
      "imagem": "../imagenes/pr9.png",
      "estoque": 63,
      "vendidos": 3,
      "categoria": "Bebidas",
      "marca": "EcoFresh",
      "apresentacao": "unidade"
    },
    {
        "id": 97,
        "nome": "Pão de Forma Integral",
        "preco": 18.66,
        "descricao": "Pacote de pão de forma integral fatiado, rico em fibras e ideal para sanduíches.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 19,
        "vendidos": 71,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 98,
        "nome": "Pão de Forma Integral",
        "preco": 7.03,
        "descricao": "Pacote de pão integral macio, pronto para consumo diário.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 70,
        "vendidos": 9,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 99,
        "nome": "Pão de Forma Integral",
        "preco": 4.19,
        "descricao": "Pacote com fatias de pão integral macio e nutritivo. Ideal para torradas e lanches.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 63,
        "vendidos": 39,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 100,
        "nome": "Croissant",
        "preco": 14.91,
        "descricao": "Croissant folhado, com massa leve e amanteigada. Aproximadamente 100g por unidade.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 35,
        "vendidos": 68,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 101,
        "nome": "Brioche",
        "preco": 8.76,
        "descricao": "Pão brioche de textura macia e leve doçura. Ideal para cafés e sanduíches gourmet.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 39,
        "vendidos": 68,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 102,
        "nome": "Pão Doce",
        "preco": 7.62,
        "descricao": "Pão doce com cobertura leve, perfeito para acompanhar cafés e chás.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 37,
        "vendidos": 6,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 103,
        "nome": "Pão de Queijo",
        "preco": 10.62,
        "descricao": "Pão de queijo tradicional mineiro, crocante por fora e macio por dentro.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 62,
        "vendidos": 5,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 104,
        "nome": "Bolo Caseiro",
        "preco": 23.66,
        "descricao": "Bolo caseiro de massa fofa, sabor tradicional. Embalagem com cerca de 800g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 57,
        "vendidos": 18,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 105,
        "nome": "Baguete",
        "preco": 24.75,
        "descricao": "Baguete crocante por fora e macia por dentro. Ideal para sanduíches ou torradas.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 22,
        "vendidos": 15,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 106,
        "nome": "Rosquinha",
        "preco": 4.75,
        "descricao": "Rosquinhas doces e crocantes, ideais para o lanche da tarde. Embalagem com 579g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 37,
        "vendidos": 41,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 107,
        "nome": "Focaccia",
        "preco": 22.04,
        "descricao": "Focaccia artesanal com ervas e azeite, ideal para acompanhar refeições ou servir como aperitivo.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 33,
        "vendidos": 39,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
    {
        "id": 108,
        "nome": "Empada",
        "preco": 7.74,
        "descricao": "Empada salgada com recheio tradicional. Ideal para lanches rápidos. Peso médio de 983g por embalagem.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 15,
        "vendidos": 60,
        "categoria": "Padaria",
        "marca": "PanNutri",
        "apresentacao": "unidade"
    },
        {
        "id": 109,
        "nome": "Granola",
        "preco": 19.15,
        "descricao": "Pacote de granola crocante com mix de grãos e frutas secas. Peso: 217g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 38,
        "vendidos": 53,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 110,
        "nome": "Aveia",
        "preco": 9.46,
        "descricao": "Pacote de aveia em flocos finos, ideal para mingaus e receitas. Peso: 734g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 40,
        "vendidos": 51,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 111,
        "nome": "Flocos de milho",
        "preco": 18.08,
        "descricao": "Cereal de milho crocante para o café da manhã. Peso: 256g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 74,
        "vendidos": 62,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 112,
        "nome": "Cereal matinal",
        "preco": 7.84,
        "descricao": "Cereal matinal doce e nutritivo para crianças e adultos. Peso: 486g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 18,
        "vendidos": 22,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 113,
        "nome": "Farelo de trigo",
        "preco": 6.21,
        "descricao": "Farelo de trigo rico em fibras, ideal para enriquecimento de receitas. Peso: 254g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 98,
        "vendidos": 49,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 114,
        "nome": "Chia",
        "preco": 14.90,
        "descricao": "Pacote de sementes de chia, fonte de ômega-3. Peso: 650g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 90,
        "vendidos": 59,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 115,
        "nome": "Linhaça",
        "preco": 4.85,
        "descricao": "Pacote de sementes de linhaça dourada. Fonte de fibras e ômega-3. Peso: 565g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 29,
        "vendidos": 59,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 116,
        "nome": "Trigo sarraceno",
        "preco": 12.99,
        "descricao": "Pacote de trigo sarraceno natural, pronto para cozimento. Peso: 534g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 11,
        "vendidos": 2,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 117,
        "nome": "Cevada",
        "preco": 20.61,
        "descricao": "Grãos de cevada para preparo de sopas, pães ou bebidas. Peso: 784g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 54,
        "vendidos": 48,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 118,
        "nome": "Mix de sementes",
        "preco": 19.07,
        "descricao": "Mistura de sementes saudáveis: chia, linhaça e girassol. Peso: 199g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 96,
        "vendidos": 27,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 119,
        "nome": "Quinoa",
        "preco": 7.18,
        "descricao": "Pacote de quinoa branca. Fonte de proteínas vegetais. Peso: 734g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 60,
        "vendidos": 47,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
    {
        "id": 120,
        "nome": "Müsli",
        "preco": 8.54,
        "descricao": "Mix europeu de cereais, frutas secas e castanhas. Peso: 517g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 71,
        "vendidos": 28,
        "categoria": "Cereais",
        "marca": "Naturale",
        "apresentacao": "unidade"
    },
        {
        "id": 121,
        "nome": "Chips de batata",
        "preco": 9.57,
        "descricao": "Pacote de chips crocantes de batata. Peso: 993g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 61,
        "vendidos": 4,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 122,
        "nome": "Doritos",
        "preco": 16.90,
        "descricao": "Snacks triangulares de milho com sabor nacho. Peso: 241g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 73,
        "vendidos": 12,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 123,
        "nome": "Salgadinho de milho",
        "preco": 6.49,
        "descricao": "Pacote de salgadinhos de milho crocante. Peso: 709g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 32,
        "vendidos": 6,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 124,
        "nome": "Biscoito salgado",
        "preco": 20.05,
        "descricao": "Biscoitos salgados leves e crocantes. Peso: 338g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 43,
        "vendidos": 50,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 125,
        "nome": "Torresmo",
        "preco": 20.39,
        "descricao": "Torresmo crocante pronto para consumo. Peso: 909g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 75,
        "vendidos": 59,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 126,
        "nome": "Pipoca",
        "preco": 12.03,
        "descricao": "Pacote de pipoca pronta e salgada. Peso: 482g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 21,
        "vendidos": 9,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 127,
        "nome": "Amendoim",
        "preco": 24.94,
        "descricao": "Amendoim torrado e salgado, pronto para consumo. Peso: 444g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 48,
        "vendidos": 67,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 128,
        "nome": "Stiksy",
        "preco": 14.34,
        "descricao": "Bastões salgados crocantes, sabor clássico. Peso: 913g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 38,
        "vendidos": 43,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 129,
        "nome": "Salgadinho de presunto",
        "preco": 7.79,
        "descricao": "Snacks crocantes sabor presunto. Peso: 330g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 89,
        "vendidos": 51,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 130,
        "nome": "Batata palha",
        "preco": 22.94,
        "descricao": "Batata palha crocante para pratos e lanches. Peso: 485g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 29,
        "vendidos": 51,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 131,
        "nome": "Nachos",
        "preco": 4.21,
        "descricao": "Tiras crocantes de milho estilo mexicano. Peso: 274g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 80,
        "vendidos": 16,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
    {
        "id": 132,
        "nome": "Salgadinho apimentado",
        "preco": 18.48,
        "descricao": "Salgadinhos crocantes com toque picante. Peso: 260g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 92,
        "vendidos": 71,
        "categoria": "Salgadinhos",
        "marca": "Crunchy",
        "apresentacao": "unidade"
    },
        {
        "id": 133,
        "nome": "Chocolate",
        "preco": 8.96,
        "descricao": "Barra de chocolate ao leite. Peso: 164g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 70,
        "vendidos": 23,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 134,
        "nome": "Bala",
        "preco": 11.76,
        "descricao": "Pacote de balas sortidas. Peso: 884g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 42,
        "vendidos": 3,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 135,
        "nome": "Leite Integral UHT 1L",
        "preco": 13.86,
        "descricao": "Leite integral longa vida em embalagem Tetra Pak (1L).",
        "imagem": "../imagenes/pr9.png",
        "estoque": 34,
        "vendidos": 37,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 136,
        "nome": "Brigadeiro",
        "preco": 18.38,
        "descricao": "Pacote com brigadeiros gourmet. Peso: 169g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 89,
        "vendidos": 71,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 137,
        "nome": "Beijinho",
        "preco": 13.76,
        "descricao": "Pacote com beijinhos tradicionais. Peso: 709g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 24,
        "vendidos": 73,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 138,
        "nome": "Pudim",
        "preco": 9.72,
        "descricao": "Pudim de leite condensado pronto para servir. Peso: 257g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 43,
        "vendidos": 77,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 139,
        "nome": "Torta doce",
        "preco": 2.71,
        "descricao": "Fatia de torta doce. Peso: 140g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 84,
        "vendidos": 32,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 140,
        "nome": "Gelatina",
        "preco": 14.92,
        "descricao": "Embalagem com gelatina pronta para consumo. Peso: 187g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 34,
        "vendidos": 12,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 141,
        "nome": "Marshmallow",
        "preco": 7.50,
        "descricao": "Pacote de marshmallows macios. Peso: 296g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 70,
        "vendidos": 18,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 142,
        "nome": "Brownie",
        "preco": 21.46,
        "descricao": "Pacote com brownies de chocolate. Peso: 404g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 17,
        "vendidos": 40,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 143,
        "nome": "Sorvete",
        "preco": 4.20,
        "descricao": "Pote de sorvete cremoso. Peso: 309g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 54,
        "vendidos": 20,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    },
    {
        "id": 144,
        "nome": "Biscoito recheado",
        "preco": 10.13,
        "descricao": "Pacote de biscoitos com recheio cremoso. Peso: 294g.",
        "imagem": "../imagenes/pr9.png",
        "estoque": 15,
        "vendidos": 37,
        "categoria": "Doces",
        "marca": "DoceVida",
        "apresentacao": "unidade"
    }
];
    localStorage.setItem("produtos", JSON.stringify(produtos));
  }
    //localStorage.removeItem("produtos");
    //localStorage.clear();
}